parameter:
  - name: max_trial_count
    description: 최대 시도 횟수
    required: true
    default_value: 2 4
  - name: is_prod
    description: 운영 여부
    required: true
    allowable_values:
      - true
      - false b
    default_value: true a