parameter:
  - name: retry
    description: 재시도 횟수
    required: true
    default_value: 2
  - name: is_test
    description: 테스트 여부
    required: true
    allowable_values:
      - true
      - false
    default_value: true